name: APK Build

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Android CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repo to CI/CD Workspace
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name : Setup Configurations
        run: npm install && cd android && chmod +x ./gradlew

      - name: Create Google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $DATA > android/app/google-services.json

      - name: Create secrets.json
        env:
          DATA: ${{ secrets.SECRETS }}
        run: echo $DATA > secrets.json

      - name: Create upload.keystore
        env:
          DATA: ${{ secrets.ANDROID_KEY_STORE_BASE64 }}
        run: echo $DATA > tmp.txt && base64 -d -i tmp.txt > android/app/upload.keystore

      - name: Build Application
        run: cd android && ./gradlew assembleRelease --no-daemon
      
      # - name: Signing APK
      #   id: sign_app
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: android/app/build/outputs/apk/release
      #     signingKeyBase64: ${{ secrets.ANDROID_KEY_STORE_BASE64 }}
      #     alias: ${{ secrets.ANDROID_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

  
      
      # - name: Release to Github Repo
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Release"
      #     files: android/app/build/outputs/apk/release/app-release.apk

      - name: Deploy using Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_DISTRIBUTION_SERVICE_ACCOUNT}}
          file: android/app/build/outputs/apk/release/app-release.apk

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test
          fields: job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}